"""
LinkCraftor Autonomous Public-Web Crawler.

The crawler package is being built and certified incrementally.
"""

from .session_models import (
    CRAWLER_SESSION_SCHEMA_VERSION,
    CrawlSession,
    CrawlSessionLimits,
    CrawlSessionStatistics,
    CrawlSessionStatus,
    TERMINAL_CRAWL_SESSION_STATUSES,
    explain_crawler_session_models_v1,
)

from .session_repository import (
    CRAWLER_SESSION_REPOSITORY_SCHEMA_VERSION,
    CRAWLER_SESSION_STORE_ROOT,
    count_crawler_sessions,
    crawler_session_exists,
    crawler_session_store_path,
    create_crawler_session,
    delete_crawler_session,
    empty_crawler_session_store,
    explain_crawler_session_repository_v1,
    get_crawler_session,
    list_crawler_sessions,
    load_crawler_session_store,
    require_crawler_session,
    save_crawler_session_store,
    update_crawler_session,
    validate_crawler_session_store,
)

from .session_coordinator import (
    ALLOWED_CRAWLER_SESSION_TRANSITIONS,
    CRAWLER_SESSION_COORDINATOR_SCHEMA_VERSION,
    cancel_crawler_session,
    complete_crawler_session,
    create_crawler_session_request,
    explain_crawler_session_coordinator_v1,
    fail_crawler_session,
    generate_crawler_session_id,
    get_crawler_session_status,
    pause_crawler_session,
    request_stop_crawler_session,
    resume_crawler_session,
    start_crawler_session,
    transition_crawler_session,
    validate_transition,
)


from .seed_models import (
    UNIVERSAL_WEB_SEED_SCHEMA_VERSION,
    UniversalWebSeed,
    UniversalWebSeedStatus,
    UniversalWebSeedType,
    explain_universal_web_seed_models_v1,
)


from .seed_repository import (
    UNIVERSAL_WEB_SEED_REPOSITORY_SCHEMA_VERSION,
    UNIVERSAL_WEB_SEED_STORE_ROOT,
    count_universal_web_seeds,
    create_universal_web_seed,
    delete_universal_web_seed,
    empty_universal_web_seed_store,
    explain_universal_web_seed_repository_v1,
    get_universal_web_seed,
    list_universal_web_seeds,
    load_universal_web_seed_store,
    require_universal_web_seed,
    save_universal_web_seed_store,
    universal_web_seed_exists,
    universal_web_seed_store_path,
    update_universal_web_seed,
    validate_universal_web_seed_store,
)


from .seed_registration_engine import (
    UNIVERSAL_WEB_SEED_REGISTRATION_SCHEMA_VERSION,
    build_universal_web_seed_registration_record,
    build_universal_web_seed_registration_result,
    explain_universal_web_seed_registration_engine_v1,
    generate_universal_web_seed_id,
    normalize_optional_crawler_session_id,
    normalize_optional_seed_id,
    normalize_registration_metadata,
    register_universal_web_seed,
)


from .seed_controls import (
    ALLOWED_UNIVERSAL_WEB_SEED_TRANSITIONS,
    PROTECTED_SEED_METADATA_KEYS,
    UNIVERSAL_WEB_SEED_CONTROLS_SCHEMA_VERSION,
    append_seed_control_event,
    archive_seed,
    build_seed_control_result,
    disable_seed,
    enable_seed,
    explain_universal_web_seed_controls_v1,
    normalize_control_actor,
    normalize_control_reason,
    restore_seed,
    update_metadata,
    update_priority,
    validate_seed_transition,
)


from .seed_protection import (
    BLOCKING_DUPLICATE_CLASSIFICATIONS,
    COMPARISON_FAMILY_BY_SEED_TYPE,
    SeedComparisonFamily,
    SeedProtectionClassification,
    SeedProtectionDecision,
    UNIVERSAL_WEB_SEED_PROTECTION_SCHEMA_VERSION,
    build_seed_comparison_target,
    build_seed_match_record,
    build_seed_protection_metadata,
    classify_seed_match,
    comparison_family_for_seed_type,
    decide_seed_protection,
    explain_universal_web_seed_protection_v1,
    generate_seed_target_fingerprint,
    hostname_from_comparison_target,
    hosts_are_related,
    inspect_seed_protection,
    normalize_domain_target,
    normalize_hostname,
    normalize_url_path,
    normalize_url_query,
    normalize_url_resource_target,
    protect_universal_web_seed,
)

__all__ = [
    "ALLOWED_CRAWLER_SESSION_TRANSITIONS",
    "CRAWLER_SESSION_COORDINATOR_SCHEMA_VERSION",
    "CRAWLER_SESSION_REPOSITORY_SCHEMA_VERSION",
    "CRAWLER_SESSION_SCHEMA_VERSION",
    "CRAWLER_SESSION_STORE_ROOT",
    "CrawlSession",
    "CrawlSessionLimits",
    "CrawlSessionStatistics",
    "CrawlSessionStatus",
    "TERMINAL_CRAWL_SESSION_STATUSES",
    "cancel_crawler_session",
    "complete_crawler_session",
    "count_crawler_sessions",
    "crawler_session_exists",
    "crawler_session_store_path",
    "create_crawler_session",
    "create_crawler_session_request",
    "delete_crawler_session",
    "empty_crawler_session_store",
    "explain_crawler_session_coordinator_v1",
    "explain_crawler_session_models_v1",
    "explain_crawler_session_repository_v1",
    "fail_crawler_session",
    "generate_crawler_session_id",
    "get_crawler_session",
    "get_crawler_session_status",
    "list_crawler_sessions",
    "load_crawler_session_store",
    "pause_crawler_session",
    "request_stop_crawler_session",
    "require_crawler_session",
    "resume_crawler_session",
    "save_crawler_session_store",
    "start_crawler_session",
    "transition_crawler_session",
    "update_crawler_session",
    "validate_crawler_session_store",
    "validate_transition",

    "UNIVERSAL_WEB_SEED_SCHEMA_VERSION",
    "UniversalWebSeed",
    "UniversalWebSeedStatus",
    "UniversalWebSeedType",
    "explain_universal_web_seed_models_v1",
    "UNIVERSAL_WEB_SEED_REPOSITORY_SCHEMA_VERSION",
    "UNIVERSAL_WEB_SEED_STORE_ROOT",
    "count_universal_web_seeds",
    "create_universal_web_seed",
    "delete_universal_web_seed",
    "empty_universal_web_seed_store",
    "explain_universal_web_seed_repository_v1",
    "get_universal_web_seed",
    "list_universal_web_seeds",
    "load_universal_web_seed_store",
    "require_universal_web_seed",
    "save_universal_web_seed_store",
    "universal_web_seed_exists",
    "universal_web_seed_store_path",
    "update_universal_web_seed",
    "validate_universal_web_seed_store",
    "UNIVERSAL_WEB_SEED_REGISTRATION_SCHEMA_VERSION",
    "build_universal_web_seed_registration_record",
    "build_universal_web_seed_registration_result",
    "explain_universal_web_seed_registration_engine_v1",
    "generate_universal_web_seed_id",
    "normalize_optional_crawler_session_id",
    "normalize_optional_seed_id",
    "normalize_registration_metadata",
    "register_universal_web_seed",
    "ALLOWED_UNIVERSAL_WEB_SEED_TRANSITIONS",
    "PROTECTED_SEED_METADATA_KEYS",
    "UNIVERSAL_WEB_SEED_CONTROLS_SCHEMA_VERSION",
    "append_seed_control_event",
    "archive_seed",
    "build_seed_control_result",
    "disable_seed",
    "enable_seed",
    "explain_universal_web_seed_controls_v1",
    "normalize_control_actor",
    "normalize_control_reason",
    "restore_seed",
    "update_metadata",
    "update_priority",
    "validate_seed_transition",
    "BLOCKING_DUPLICATE_CLASSIFICATIONS",
    "COMPARISON_FAMILY_BY_SEED_TYPE",
    "SeedComparisonFamily",
    "SeedProtectionClassification",
    "SeedProtectionDecision",
    "UNIVERSAL_WEB_SEED_PROTECTION_SCHEMA_VERSION",
    "build_seed_comparison_target",
    "build_seed_match_record",
    "build_seed_protection_metadata",
    "classify_seed_match",
    "comparison_family_for_seed_type",
    "decide_seed_protection",
    "explain_universal_web_seed_protection_v1",
    "generate_seed_target_fingerprint",
    "hostname_from_comparison_target",
    "hosts_are_related",
    "inspect_seed_protection",
    "normalize_domain_target",
    "normalize_hostname",
    "normalize_url_path",
    "normalize_url_query",
    "normalize_url_resource_target",
    "protect_universal_web_seed",]
